[package]
authors = ["github.scott@gmail.com"]
edition = "2021"
name = "rbasefind"
version = "0.1.3"

[dependencies]
byteorder = "1.4.3"
clap = "3"
fnv = "1.0.7"
num_cpus = "1.13.1"
pbr = "1.0.4"
regex = "1.6.0"
