[package]
name = "rbasefind"
version = "0.1.3"
authors = ["github.scott@gmail.com"]
edition = "2021"

[dependencies]
byteorder = "1.3.4"
clap = "3.2.10"
fnv = "1.0.7"
num_cpus = "1.13.0"
regex = "1.3.9"
pbr = "1.0.3"
